"""add rooms

Revision ID: 5ad22d3b0943
Revises: ca4549b0354f
Create Date: 2025-05-01 15:22:32.975312

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5ad22d3b0943"
down_revision: Union[str, None] = "ca4549b0354f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("rooms", "hotel_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint("rooms_hotel_id_fkey", "rooms", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "rooms_hotel_id_fkey", "rooms", "hotels", ["hotel_id"], ["id"]
    )
    op.alter_column("rooms", "hotel_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
