"""add rooms

Revision ID: 687dc646a5b7
Revises: 5ad22d3b0943
Create Date: 2025-05-03 15:20:29.629722

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "687dc646a5b7"
down_revision: Union[str, None] = "5ad22d3b0943"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("rooms", "hotel_id", existing_type=sa.INTEGER(), nullable=False)
    op.create_foreign_key(None, "rooms", "hotels", ["hotel_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "rooms", type_="foreignkey")
    op.alter_column("rooms", "hotel_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
